//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLTS.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebQLTS.Common.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phạm Thị Quyên.
        /// </summary>
        public static string DefaultUser {
            get {
                return ResourceManager.GetString("DefaultUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete multiple from databse return 0.
        /// </summary>
        public static string DevMsg_BatchDeleteFailed {
            get {
                return ResourceManager.GetString("DevMsg_BatchDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete from datase return 0.
        /// </summary>
        public static string DevMsg_DeleteFailed {
            get {
                return ResourceManager.GetString("DevMsg_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Code failed.
        /// </summary>
        public static string DevMsg_DuplicateCodeFailed {
            get {
                return ResourceManager.GetString("DevMsg_DuplicateCodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch an exeption.
        /// </summary>
        public static string DevMsg_Exception {
            get {
                return ResourceManager.GetString("DevMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter data from database return 0.
        /// </summary>
        public static string DevMsg_FilterFailed {
            get {
                return ResourceManager.GetString("DevMsg_FilterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all records from database return 0.
        /// </summary>
        public static string DevMsg_GetAllFailed {
            get {
                return ResourceManager.GetString("DevMsg_GetAllFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get detail one from database return 0.
        /// </summary>
        public static string DevMsg_GetDetailOneFailed {
            get {
                return ResourceManager.GetString("DevMsg_GetDetailOneFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get max code failed.
        /// </summary>
        public static string DevMsg_GetMaxCodeFailed {
            get {
                return ResourceManager.GetString("DevMsg_GetMaxCodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert to database return 0.
        /// </summary>
        public static string DevMsg_InsertFailed {
            get {
                return ResourceManager.GetString("DevMsg_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update to databse return 0.
        /// </summary>
        public static string DevMsg_UpdateFailed {
            get {
                return ResourceManager.GetString("DevMsg_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more validation errors occured.
        /// </summary>
        public static string DevMsg_ValidateFailed {
            get {
                return ResourceManager.GetString("DevMsg_ValidateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com.vn/errorcode/9.
        /// </summary>
        public static string MoreInfo_BatchDeleteFailed {
            get {
                return ResourceManager.GetString("MoreInfo_BatchDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com.vn/errorcode/8.
        /// </summary>
        public static string MoreInfo_DeleteFailed {
            get {
                return ResourceManager.GetString("MoreInfo_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com.vn/errorcode/2.
        /// </summary>
        public static string MoreInfo_DuplicateCodeFailed {
            get {
                return ResourceManager.GetString("MoreInfo_DuplicateCodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com.vn/errorcode/1.
        /// </summary>
        public static string MoreInfo_Exception {
            get {
                return ResourceManager.GetString("MoreInfo_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com.vn/errorcode/10.
        /// </summary>
        public static string MoreInfo_FilterFailed {
            get {
                return ResourceManager.GetString("MoreInfo_FilterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com.vn/errorcode/4.
        /// </summary>
        public static string MoreInfo_GetAllFailed {
            get {
                return ResourceManager.GetString("MoreInfo_GetAllFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com.vn/errorcode/5.
        /// </summary>
        public static string MoreInfo_GetDetailOneFailed {
            get {
                return ResourceManager.GetString("MoreInfo_GetDetailOneFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com.vn/errorcode/12.
        /// </summary>
        public static string MoreInfo_GetMaxCodeFailed {
            get {
                return ResourceManager.GetString("MoreInfo_GetMaxCodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com.vn/errorcode/6.
        /// </summary>
        public static string MoreInfo_InsertFailed {
            get {
                return ResourceManager.GetString("MoreInfo_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com.vn/errorcode/7.
        /// </summary>
        public static string MoreInfo_UpdateFailed {
            get {
                return ResourceManager.GetString("MoreInfo_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com.vn/errorcode/11.
        /// </summary>
        public static string MoreInfo_ValidateFailed {
            get {
                return ResourceManager.GetString("MoreInfo_ValidateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_BatchDelete.
        /// </summary>
        public static string Proc_BatchDelete {
            get {
                return ResourceManager.GetString("Proc_BatchDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_DeleteOne.
        /// </summary>
        public static string Proc_DeleteOne {
            get {
                return ResourceManager.GetString("Proc_DeleteOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_DuplicateCode.
        /// </summary>
        public static string Proc_DuplicateCode {
            get {
                return ResourceManager.GetString("Proc_DuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetAll.
        /// </summary>
        public static string Proc_GetAll {
            get {
                return ResourceManager.GetString("Proc_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetDetailOne.
        /// </summary>
        public static string Proc_GetDetailOne {
            get {
                return ResourceManager.GetString("Proc_GetDetailOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_InsertOne.
        /// </summary>
        public static string Proc_InsertOne {
            get {
                return ResourceManager.GetString("Proc_InsertOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_Update.
        /// </summary>
        public static string Proc_Update {
            get {
                return ResourceManager.GetString("Proc_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nhiều bản ghi thất bại.
        /// </summary>
        public static string UserMsg_BatchDeleteFailed {
            get {
                return ResourceManager.GetString("UserMsg_BatchDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa bản ghi thất bại.
        /// </summary>
        public static string UserMsg_DeleteFailed {
            get {
                return ResourceManager.GetString("UserMsg_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy mã trùng thất bại.
        /// </summary>
        public static string UserMsg_DuplicateCodeFailed {
            get {
                return ResourceManager.GetString("UserMsg_DuplicateCodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ MISA.
        /// </summary>
        public static string UserMsg_Exception {
            get {
                return ResourceManager.GetString("UserMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lọc dữ liệu từ database thất bại.
        /// </summary>
        public static string UserMsg_FilterFailed {
            get {
                return ResourceManager.GetString("UserMsg_FilterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy toàn bộ bản ghi thất bại.
        /// </summary>
        public static string UserMsg_GetAllFailed {
            get {
                return ResourceManager.GetString("UserMsg_GetAllFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy bản ghi theo ID thất bại.
        /// </summary>
        public static string UserMsg_GetDetailOneFailed {
            get {
                return ResourceManager.GetString("UserMsg_GetDetailOneFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy mã lớn nhất của bảng thất bại.
        /// </summary>
        public static string UserMsg_GetMaxCodeFailed {
            get {
                return ResourceManager.GetString("UserMsg_GetMaxCodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới bản ghi thất bại.
        /// </summary>
        public static string UserMsg_InsertFailed {
            get {
                return ResourceManager.GetString("UserMsg_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa bản ghi thất bại.
        /// </summary>
        public static string UserMsg_UpdateFailed {
            get {
                return ResourceManager.GetString("UserMsg_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ.
        /// </summary>
        public static string UserMsg_ValidateFailed {
            get {
                return ResourceManager.GetString("UserMsg_ValidateFailed", resourceCulture);
            }
        }
    }
}
